refactor(build): prefix images with branch name (#70)
refactor(build): prefix images with branch name

Refactored the push script to:
- prefix the branch name to docker images
- push a commit tagged image to ci repo.
- push the images to quay
- use a tagged minikube instead of latest
- perform full clone of the repo in travis

By default travis does a shallow clone with a depth of
50 commits. This will cause issues with commands like
`git tag` not displaying the current/latest status.

This PR also removes the second (redundant) build of the
provisioner image creation.

Signed-off-by: kmova <kiran.mova@openebs.io>

diff --git a/buildscripts/push b/buildscripts/push
--- a/buildscripts/push
+++ b/buildscripts/push
@@ -16,22 +16,94 @@
 
 set -e
 
-IMAGEID=$( sudo docker images -q ${DIMAGE}:ci )
+if [ -z ${DIMAGE} ];
+then
+  echo "Error: DIMAGE is not specified";
+  exit 1
+fi
 
-if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
-then 
-  sudo docker login -u "${DNAME}" -p "${DPASS}"; 
-  sudo docker push ${DIMAGE}:ci ; 
-  if [ ! -z "${TRAVIS_TAG}" ] ; 
+IMAGEID=$( docker images -q ${DIMAGE}:ci )
+echo $IMAGEID 
+if [ -z ${IMAGEID} ];
+then
+  echo "Error: unable to get IMAGEID for ${DIMAGE}:ci";
+  exit 1
+fi
+
+# Generate a uniqe tag based on the commit and tag
+BUILD_ID=$(git describe --tags --always)
+
+# Determine the current branch
+CURRENT_BRANCH=""
+if [ -z ${TRAVIS_BRANCH} ];
+then
+  CURRENT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
+else
+  CURRENT_BRANCH=${TRAVIS_BRANCH}
+fi
+
+#Depending on the branch where builds are generated, 
+# set the tag CI (fixed) and build tags.
+BUILD_TAG="${CURRENT_BRANCH}-${BUILD_ID}"
+CI_TAG="${CURRENT_BRANCH}-ci"
+if [ ${CURRENT_BRANCH} = "release" ]; then
+  CI_TAG="ci"
+fi
+
+echo "Set the fixed ci image tag as: ${CI_TAG}"
+echo "Set the build/unique image tag as: ${BUILD_TAG}"
+
+function TagAndPushImage() {
+  REPO="$1"
+  TAG="$2"
+  
+  IMAGE_URI="${REPO}:${TAG}";
+  sudo docker tag ${IMAGEID} ${IMAGE_URI};
+  echo " push ${IMAGE_URI}";
+  sudo docker push ${IMAGE_URI};
+}
+
+if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
+then
+  sudo docker login -u "${DNAME}" -p "${DPASS}";
+
+  # Push CI tagged image - :ci or :branch-ci
+  TagAndPushImage "${DIMAGE}" "${CI_TAG}"
+
+  # Push unique tagged image - :master-<uuid> or :branch-<uuid>
+  # This unique/build image will be pushed to corresponding ci repo. 
+  TagAndPushImage "${DIMAGE}-ci" "${BUILD_TAG}"
+
+
+  if [ ! -z "${TRAVIS_TAG}" ] ;
   then
-    #Push the release tag image to docker hub repository
-    #When a git hub is tagged with a release, the travis will 
-    #hold the release tag in env TRAVIS_TAG
-    sudo docker tag ${IMAGEID} ${DIMAGE}:${TRAVIS_TAG}
-    sudo docker push ${DIMAGE}:${TRAVIS_TAG}; 
-    sudo docker tag ${IMAGEID} ${DIMAGE}:latest
-    sudo docker push ${DIMAGE}:latest; 
+    # Push with different tags if tagged as a release
+    # When github is tagged with a release, then Travis will
+    # set the release tag in env TRAVIS_TAG
+    TagAndPushImage "${DIMAGE}" "${TRAVIS_TAG}"
+    TagAndPushImage "${DIMAGE}" "latest"
   fi;
 else
-  echo "No docker credentials provided. Skip uploading ${DIMAGE}:ci to docker hub"; 
+  echo "No docker credentials provided. Skip uploading ${DIMAGE} to docker hub";
 fi;
+
+# Push ci image to quay.io for security scanning
+if [ ! -z "${QNAME}" ] && [ ! -z "${QPASS}" ]; 
+then 
+  sudo docker login -u "${QNAME}" -p "${QPASS}" quay.io;
+
+  # Push CI tagged image - :ci or :branch-ci
+  TagAndPushImage "quay.io/${DIMAGE}" "${CI_TAG}"
+
+  if [ ! -z "${TRAVIS_TAG}" ] ;
+  then
+    # Push with different tags if tagged as a release
+    # When github is tagged with a release, then Travis will
+    # set the release tag in env TRAVIS_TAG
+    TagAndPushImage "quay.io/${DIMAGE}" "${TRAVIS_TAG}"
+    TagAndPushImage "quay.io/${DIMAGE}" "latest"
+  fi;
+else
+  echo "No docker credentials provided. Skip uploading ${DIMAGE} to quay";
+fi;
+
